#############################################################################
# Makefile for building: hellyeah
# Generated by qmake (3.1) (Qt 6.10.0)
# Project:  hellyeah.pro
# Template: app
# Command: /usr/bin/qmake6 -o Makefile hellyeah.pro
#############################################################################

MAKEFILE      = Makefile

EQ            = =

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_SQL_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 -Wall -Wextra -mno-direct-extern-access -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -O2 -std=gnu++1z -Wall -Wextra -mno-direct-extern-access -D_REENTRANT $(DEFINES)
INCPATH       = -I. -I/usr/include/qt6 -I/usr/include/qt6/QtWidgets -I/usr/include/qt6/QtGui -I/usr/include/qt6/QtNetwork -I/usr/include/qt6/QtSql -I/usr/include/qt6/QtCore -I. -I/usr/lib/qt6/mkspecs/linux-g++
QMAKE         = /usr/bin/qmake6
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /usr/bin/qmake6 -install qinstall
QINSTALL_PROGRAM = /usr/bin/qmake6 -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = hellyeah1.0.0
DISTDIR = /home/xi/dev/hellyeah/.tmp/hellyeah1.0.0
LINK          = g++
LFLAGS        = -Wl,-O1 -Wl,-rpath,/usr/lib -Wl,-rpath-link,/usr/lib
LIBS          = $(SUBLIBS) -ldl -lm /usr/lib/libQt6Widgets.so /usr/lib/libQt6Gui.so /usr/lib/libGLX.so /usr/lib/libOpenGL.so /usr/lib/libQt6Network.so /usr/lib/libQt6Sql.so /usr/lib/libQt6Core.so -lpthread -lGLX -lOpenGL   
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = src/main.cpp \
		src/api/HifiClient.cpp \
		src/player/AudioPlayer.cpp \
		src/ui/MainWindow.cpp \
		src/ui/TrackItemWidget.cpp \
		src/ui/FavoriteCard.cpp \
		src/ui/AlbumCard.cpp \
		src/db/DatabaseManager.cpp \
		src/net/DownloadManager.cpp \
		src/ui/CreateAlbumDialog.cpp moc_HifiClient.cpp \
		moc_AudioPlayer.cpp \
		moc_MainWindow.cpp \
		moc_TrackItemWidget.cpp \
		moc_FavoriteCard.cpp \
		moc_AlbumCard.cpp \
		moc_DatabaseManager.cpp \
		moc_DownloadManager.cpp \
		moc_CreateAlbumDialog.cpp
OBJECTS       = main.o \
		HifiClient.o \
		AudioPlayer.o \
		MainWindow.o \
		TrackItemWidget.o \
		FavoriteCard.o \
		AlbumCard.o \
		DatabaseManager.o \
		DownloadManager.o \
		CreateAlbumDialog.o \
		moc_HifiClient.o \
		moc_AudioPlayer.o \
		moc_MainWindow.o \
		moc_TrackItemWidget.o \
		moc_FavoriteCard.o \
		moc_AlbumCard.o \
		moc_DatabaseManager.o \
		moc_DownloadManager.o \
		moc_CreateAlbumDialog.o
DIST          = /usr/lib/qt6/mkspecs/features/spec_pre.prf \
		/usr/lib/qt6/mkspecs/common/unix.conf \
		/usr/lib/qt6/mkspecs/common/linux.conf \
		/usr/lib/qt6/mkspecs/common/sanitize.conf \
		/usr/lib/qt6/mkspecs/common/gcc-base.conf \
		/usr/lib/qt6/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/qt6/mkspecs/common/g++-base.conf \
		/usr/lib/qt6/mkspecs/common/g++-unix.conf \
		/usr/lib/qt6/mkspecs/qconfig.pri \
		/usr/lib/qt6/mkspecs/modules/qt_KDSingleApplication.pri \
		/usr/lib/qt6/mkspecs/modules/qt_KDSoapClient.pri \
		/usr/lib/qt6/mkspecs/modules/qt_KDSoapServer.pri \
		/usr/lib/qt6/mkspecs/modules/qt_KF6UserFeedbackCore.pri \
		/usr/lib/qt6/mkspecs/modules/qt_KF6UserFeedbackWidgets.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_bluetooth.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_connectivity_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_core5compat.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_core5compat_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_designer.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_designer_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_eglfs_kms_gbm_support_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_example_icons_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_examples_asset_downloader_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_ffmpegmediapluginimpl_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_help.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_help_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_hunspellinputmethod.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_hunspellinputmethod_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_labsanimation.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_labsanimation_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_labsfolderlistmodel.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_labsfolderlistmodel_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_labsplatform.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_labsplatform_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_labsqmlmodels.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_labsqmlmodels_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_labssettings.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_labssettings_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_labssharedimage.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_labssharedimage_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_labssynchronizer.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_labssynchronizer_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_labswavefrontmesh.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_labswavefrontmesh_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_linguist.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_location.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_location_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_multimedia.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_multimedia_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_multimediaquick_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_multimediatestlibprivate_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_nfc.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_nfc_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_openglwidgets.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_pdf.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_pdf_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_pdfquick.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_pdfquick_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_pdfwidgets.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_pdfwidgets_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_positioning.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_positioning_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_positioningquick.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_positioningquick_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qdoccatch_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qdoccatchconversions_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qdoccatchgenerators_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qml.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qml_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qmlassetdownloader.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qmlassetdownloader_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qmlcompiler.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qmlcompiler_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qmlcore.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qmlcore_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qmldom_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qmlformat_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qmlintegration.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qmllocalstorage.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qmllocalstorage_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qmlls_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qmlmeta.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qmlmeta_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qmlmodels.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qmlmodels_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qmlnetwork.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qmlnetwork_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qmltest_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qmltoolingsettings_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qmltyperegistrar_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qmlworkerscript_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qmlxmllistmodel.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qmlxmllistmodel_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quick.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quick3d.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quick3d_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quick3dassetimport.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quick3dassetimport_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quick3dassetutils.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quick3dassetutils_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quick3deffects.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quick3dglslparser_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quick3dhelpers.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quick3dhelpers_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quick3dhelpersimpl.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quick3dhelpersimpl_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quick3diblbaker.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quick3diblbaker_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quick3dparticleeffects.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quick3dparticles.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quick3dparticles_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quick3druntimerender.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quick3druntimerender_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quick3dspatialaudio_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quick3dutils.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quick3dutils_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quick3dxr.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quick3dxr_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quick_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2basic.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2basic_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2basicstyleimpl.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2basicstyleimpl_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2fluentwinui3styleimpl.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2fluentwinui3styleimpl_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2fusion.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2fusion_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2fusionstyleimpl.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2fusionstyleimpl_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2imagine.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2imagine_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2imaginestyleimpl.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2impl.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2impl_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2material.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2material_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2materialstyleimpl.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2materialstyleimpl_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2universal.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2universal_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2universalstyleimpl.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2universalstyleimpl_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrolstestutilsprivate_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickdialogs2.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickdialogs2_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickdialogs2quickimpl.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickdialogs2quickimpl_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickdialogs2utils.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickdialogs2utils_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickeffects.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickeffects_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quicklayouts.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quicklayouts_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickshapes_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickshapesdesignhelpers_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quicktemplates2.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quicktestutilsprivate_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quicktimeline.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quicktimeline_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quicktimelineblendtrees.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quicktimelineblendtrees_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickvectorimage.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickvectorimage_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickvectorimagegenerator_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickvectorimagehelpers.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickvectorimagehelpers_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickwidgets.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_sensors.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_sensors_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_sensorsquick.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_sensorsquick_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_shadertools.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_shadertools_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_spatialaudio.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_spatialaudio_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_svg.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_svg_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_svgwidgets.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_testinternals_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_texttospeech.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_texttospeech_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_tools_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_uiplugin.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_uitools.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_uitools_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_virtualkeyboard.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_virtualkeyboard_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_virtualkeyboardqml.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_virtualkeyboardqml_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_virtualkeyboardsettings.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_virtualkeyboardsettings_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_wayland_egl_compositor_hw_integration_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_waylandclient.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_waylandclient_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_waylandclientfeatures_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_waylandcompositor.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_waylandcompositor_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_waylandcompositoriviapplication.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_waylandcompositoriviapplication_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_waylandcompositorpresentationtime.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_waylandcompositorpresentationtime_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_waylandcompositorwlshell.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_waylandcompositorwlshell_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_waylandcompositorxdgshell.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_waylandcompositorxdgshell_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_waylandglobal_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_webchannel.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_webchannel_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_webchannelquick.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_webchannelquick_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_webenginecore.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_webenginecore_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_webenginequick.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_webenginequick_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_webenginequickdelegatesqml.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_webenginewidgets.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_websockets.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_websockets_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_wl_shell_integration_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_QCoroCore.pri \
		/usr/lib/qt6/mkspecs/modules/qt_QCoroCoro.pri \
		/usr/lib/qt6/mkspecs/modules/qt_QCoroDBus.pri \
		/usr/lib/qt6/mkspecs/modules/qt_QCoroNetwork.pri \
		/usr/lib/qt6/mkspecs/modules/qt_QCoroQml.pri \
		/usr/lib/qt6/mkspecs/modules/qt_QCoroQuick.pri \
		/usr/lib/qt6/mkspecs/modules/qt_QCoroTest.pri \
		/usr/lib/qt6/mkspecs/modules/qt_QCoroWebSockets.pri \
		/usr/lib/qt6/mkspecs/features/qt_functions.prf \
		/usr/lib/qt6/mkspecs/features/qt_config.prf \
		/usr/lib/qt6/mkspecs/linux-g++/qmake.conf \
		/usr/lib/qt6/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/lib/qt6/mkspecs/features/exclusive_builds.prf \
		/usr/lib/qt6/mkspecs/features/toolchain.prf \
		/usr/lib/qt6/mkspecs/features/default_pre.prf \
		/usr/lib/qt6/mkspecs/features/resolve_config.prf \
		/usr/lib/qt6/mkspecs/features/default_post.prf \
		/usr/lib/qt6/mkspecs/features/cmdline.prf \
		/usr/lib/qt6/mkspecs/features/warn_on.prf \
		/usr/lib/qt6/mkspecs/features/permissions.prf \
		/usr/lib/qt6/mkspecs/features/qt.prf \
		/usr/lib/qt6/mkspecs/features/resources_functions.prf \
		/usr/lib/qt6/mkspecs/features/resources.prf \
		/usr/lib/qt6/mkspecs/features/moc.prf \
		/usr/lib/qt6/mkspecs/features/link_ltcg.prf \
		/usr/lib/qt6/mkspecs/features/unix/opengl.prf \
		/usr/lib/qt6/mkspecs/features/uic.prf \
		/usr/lib/qt6/mkspecs/features/unix/no_direct_extern_access.prf \
		/usr/lib/qt6/mkspecs/features/unix/thread.prf \
		/usr/lib/qt6/mkspecs/features/qmake_use.prf \
		/usr/lib/qt6/mkspecs/features/file_copies.prf \
		/usr/lib/qt6/mkspecs/features/testcase_targets.prf \
		/usr/lib/qt6/mkspecs/features/exceptions.prf \
		/usr/lib/qt6/mkspecs/features/yacc.prf \
		/usr/lib/qt6/mkspecs/features/lex.prf \
		hellyeah.pro src/api/HifiClient.hpp \
		src/player/AudioPlayer.hpp \
		src/ui/MainWindow.hpp \
		src/ui/TrackItemWidget.hpp \
		src/ui/FavoriteCard.hpp \
		src/ui/AlbumCard.hpp \
		src/db/DatabaseManager.hpp \
		src/net/DownloadManager.hpp \
		src/ui/CreateAlbumDialog.hpp src/main.cpp \
		src/api/HifiClient.cpp \
		src/player/AudioPlayer.cpp \
		src/ui/MainWindow.cpp \
		src/ui/TrackItemWidget.cpp \
		src/ui/FavoriteCard.cpp \
		src/ui/AlbumCard.cpp \
		src/db/DatabaseManager.cpp \
		src/net/DownloadManager.cpp \
		src/ui/CreateAlbumDialog.cpp
QMAKE_TARGET  = hellyeah
DESTDIR       = 
TARGET        = hellyeah


first: all
####### Build rules

hellyeah:  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET)  $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: hellyeah.pro /usr/lib/qt6/mkspecs/linux-g++/qmake.conf /usr/lib/qt6/mkspecs/features/spec_pre.prf \
		/usr/lib/qt6/mkspecs/common/unix.conf \
		/usr/lib/qt6/mkspecs/common/linux.conf \
		/usr/lib/qt6/mkspecs/common/sanitize.conf \
		/usr/lib/qt6/mkspecs/common/gcc-base.conf \
		/usr/lib/qt6/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/qt6/mkspecs/common/g++-base.conf \
		/usr/lib/qt6/mkspecs/common/g++-unix.conf \
		/usr/lib/qt6/mkspecs/qconfig.pri \
		/usr/lib/qt6/mkspecs/modules/qt_KDSingleApplication.pri \
		/usr/lib/qt6/mkspecs/modules/qt_KDSoapClient.pri \
		/usr/lib/qt6/mkspecs/modules/qt_KDSoapServer.pri \
		/usr/lib/qt6/mkspecs/modules/qt_KF6UserFeedbackCore.pri \
		/usr/lib/qt6/mkspecs/modules/qt_KF6UserFeedbackWidgets.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_bluetooth.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_connectivity_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_core5compat.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_core5compat_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_designer.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_designer_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_eglfs_kms_gbm_support_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_example_icons_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_examples_asset_downloader_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_ffmpegmediapluginimpl_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_help.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_help_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_hunspellinputmethod.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_hunspellinputmethod_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_labsanimation.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_labsanimation_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_labsfolderlistmodel.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_labsfolderlistmodel_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_labsplatform.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_labsplatform_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_labsqmlmodels.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_labsqmlmodels_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_labssettings.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_labssettings_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_labssharedimage.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_labssharedimage_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_labssynchronizer.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_labssynchronizer_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_labswavefrontmesh.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_labswavefrontmesh_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_linguist.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_location.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_location_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_multimedia.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_multimedia_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_multimediaquick_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_multimediatestlibprivate_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_nfc.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_nfc_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_openglwidgets.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_pdf.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_pdf_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_pdfquick.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_pdfquick_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_pdfwidgets.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_pdfwidgets_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_positioning.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_positioning_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_positioningquick.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_positioningquick_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qdoccatch_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qdoccatchconversions_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qdoccatchgenerators_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qml.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qml_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qmlassetdownloader.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qmlassetdownloader_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qmlcompiler.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qmlcompiler_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qmlcore.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qmlcore_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qmldom_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qmlformat_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qmlintegration.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qmllocalstorage.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qmllocalstorage_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qmlls_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qmlmeta.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qmlmeta_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qmlmodels.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qmlmodels_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qmlnetwork.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qmlnetwork_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qmltest_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qmltoolingsettings_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qmltyperegistrar_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qmlworkerscript_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qmlxmllistmodel.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qmlxmllistmodel_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quick.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quick3d.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quick3d_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quick3dassetimport.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quick3dassetimport_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quick3dassetutils.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quick3dassetutils_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quick3deffects.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quick3dglslparser_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quick3dhelpers.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quick3dhelpers_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quick3dhelpersimpl.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quick3dhelpersimpl_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quick3diblbaker.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quick3diblbaker_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quick3dparticleeffects.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quick3dparticles.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quick3dparticles_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quick3druntimerender.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quick3druntimerender_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quick3dspatialaudio_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quick3dutils.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quick3dutils_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quick3dxr.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quick3dxr_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quick_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2basic.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2basic_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2basicstyleimpl.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2basicstyleimpl_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2fluentwinui3styleimpl.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2fluentwinui3styleimpl_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2fusion.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2fusion_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2fusionstyleimpl.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2fusionstyleimpl_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2imagine.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2imagine_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2imaginestyleimpl.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2impl.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2impl_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2material.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2material_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2materialstyleimpl.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2materialstyleimpl_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2universal.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2universal_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2universalstyleimpl.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2universalstyleimpl_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrolstestutilsprivate_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickdialogs2.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickdialogs2_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickdialogs2quickimpl.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickdialogs2quickimpl_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickdialogs2utils.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickdialogs2utils_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickeffects.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickeffects_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quicklayouts.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quicklayouts_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickshapes_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickshapesdesignhelpers_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quicktemplates2.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quicktestutilsprivate_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quicktimeline.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quicktimeline_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quicktimelineblendtrees.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quicktimelineblendtrees_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickvectorimage.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickvectorimage_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickvectorimagegenerator_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickvectorimagehelpers.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickvectorimagehelpers_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickwidgets.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_sensors.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_sensors_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_sensorsquick.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_sensorsquick_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_shadertools.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_shadertools_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_spatialaudio.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_spatialaudio_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_svg.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_svg_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_svgwidgets.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_testinternals_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_texttospeech.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_texttospeech_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_tools_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_uiplugin.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_uitools.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_uitools_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_virtualkeyboard.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_virtualkeyboard_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_virtualkeyboardqml.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_virtualkeyboardqml_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_virtualkeyboardsettings.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_virtualkeyboardsettings_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_wayland_egl_compositor_hw_integration_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_waylandclient.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_waylandclient_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_waylandclientfeatures_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_waylandcompositor.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_waylandcompositor_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_waylandcompositoriviapplication.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_waylandcompositoriviapplication_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_waylandcompositorpresentationtime.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_waylandcompositorpresentationtime_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_waylandcompositorwlshell.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_waylandcompositorwlshell_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_waylandcompositorxdgshell.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_waylandcompositorxdgshell_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_waylandglobal_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_webchannel.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_webchannel_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_webchannelquick.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_webchannelquick_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_webenginecore.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_webenginecore_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_webenginequick.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_webenginequick_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_webenginequickdelegatesqml.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_webenginewidgets.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_websockets.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_websockets_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_wl_shell_integration_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_QCoroCore.pri \
		/usr/lib/qt6/mkspecs/modules/qt_QCoroCoro.pri \
		/usr/lib/qt6/mkspecs/modules/qt_QCoroDBus.pri \
		/usr/lib/qt6/mkspecs/modules/qt_QCoroNetwork.pri \
		/usr/lib/qt6/mkspecs/modules/qt_QCoroQml.pri \
		/usr/lib/qt6/mkspecs/modules/qt_QCoroQuick.pri \
		/usr/lib/qt6/mkspecs/modules/qt_QCoroTest.pri \
		/usr/lib/qt6/mkspecs/modules/qt_QCoroWebSockets.pri \
		/usr/lib/qt6/mkspecs/features/qt_functions.prf \
		/usr/lib/qt6/mkspecs/features/qt_config.prf \
		/usr/lib/qt6/mkspecs/linux-g++/qmake.conf \
		/usr/lib/qt6/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/lib/qt6/mkspecs/features/exclusive_builds.prf \
		/usr/lib/qt6/mkspecs/features/toolchain.prf \
		/usr/lib/qt6/mkspecs/features/default_pre.prf \
		/usr/lib/qt6/mkspecs/features/resolve_config.prf \
		/usr/lib/qt6/mkspecs/features/default_post.prf \
		/usr/lib/qt6/mkspecs/features/cmdline.prf \
		/usr/lib/qt6/mkspecs/features/warn_on.prf \
		/usr/lib/qt6/mkspecs/features/permissions.prf \
		/usr/lib/qt6/mkspecs/features/qt.prf \
		/usr/lib/qt6/mkspecs/features/resources_functions.prf \
		/usr/lib/qt6/mkspecs/features/resources.prf \
		/usr/lib/qt6/mkspecs/features/moc.prf \
		/usr/lib/qt6/mkspecs/features/link_ltcg.prf \
		/usr/lib/qt6/mkspecs/features/unix/opengl.prf \
		/usr/lib/qt6/mkspecs/features/uic.prf \
		/usr/lib/qt6/mkspecs/features/unix/no_direct_extern_access.prf \
		/usr/lib/qt6/mkspecs/features/unix/thread.prf \
		/usr/lib/qt6/mkspecs/features/qmake_use.prf \
		/usr/lib/qt6/mkspecs/features/file_copies.prf \
		/usr/lib/qt6/mkspecs/features/testcase_targets.prf \
		/usr/lib/qt6/mkspecs/features/exceptions.prf \
		/usr/lib/qt6/mkspecs/features/yacc.prf \
		/usr/lib/qt6/mkspecs/features/lex.prf \
		hellyeah.pro \
		/usr/lib/libQt6Widgets.prl \
		/usr/lib/libQt6Gui.prl \
		/usr/lib/libQt6Network.prl \
		/usr/lib/libQt6Sql.prl \
		/usr/lib/libQt6Core.prl
	$(QMAKE) -o Makefile hellyeah.pro
/usr/lib/qt6/mkspecs/features/spec_pre.prf:
/usr/lib/qt6/mkspecs/common/unix.conf:
/usr/lib/qt6/mkspecs/common/linux.conf:
/usr/lib/qt6/mkspecs/common/sanitize.conf:
/usr/lib/qt6/mkspecs/common/gcc-base.conf:
/usr/lib/qt6/mkspecs/common/gcc-base-unix.conf:
/usr/lib/qt6/mkspecs/common/g++-base.conf:
/usr/lib/qt6/mkspecs/common/g++-unix.conf:
/usr/lib/qt6/mkspecs/qconfig.pri:
/usr/lib/qt6/mkspecs/modules/qt_KDSingleApplication.pri:
/usr/lib/qt6/mkspecs/modules/qt_KDSoapClient.pri:
/usr/lib/qt6/mkspecs/modules/qt_KDSoapServer.pri:
/usr/lib/qt6/mkspecs/modules/qt_KF6UserFeedbackCore.pri:
/usr/lib/qt6/mkspecs/modules/qt_KF6UserFeedbackWidgets.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_bluetooth.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_bluetooth_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_concurrent.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_connectivity_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_core.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_core5compat.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_core5compat_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_core_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_dbus.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_dbus_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_designer.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_designer_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_designercomponents_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_eglfs_kms_gbm_support_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_example_icons_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_examples_asset_downloader_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_fb_support_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_ffmpegmediapluginimpl_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_gui.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_gui_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_help.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_help_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_hunspellinputmethod.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_hunspellinputmethod_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_input_support_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_kms_support_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_labsanimation.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_labsanimation_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_labsfolderlistmodel.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_labsfolderlistmodel_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_labsplatform.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_labsplatform_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_labsqmlmodels.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_labsqmlmodels_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_labssettings.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_labssettings_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_labssharedimage.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_labssharedimage_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_labssynchronizer.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_labssynchronizer_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_labswavefrontmesh.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_labswavefrontmesh_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_linguist.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_location.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_location_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_multimedia.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_multimedia_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_multimediaquick_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_multimediatestlibprivate_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_multimediawidgets.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_network.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_network_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_nfc.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_nfc_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_opengl.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_opengl_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_openglwidgets.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_packetprotocol_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_pdf.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_pdf_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_pdfquick.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_pdfquick_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_pdfwidgets.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_pdfwidgets_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_positioning.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_positioning_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_positioningquick.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_positioningquick_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_printsupport.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_printsupport_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_qdoccatch_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_qdoccatchconversions_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_qdoccatchgenerators_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_qml.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_qml_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_qmlassetdownloader.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_qmlassetdownloader_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_qmlcompiler.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_qmlcompiler_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_qmlcore.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_qmlcore_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_qmldebug_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_qmldom_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_qmlformat_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_qmlintegration.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_qmllocalstorage.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_qmllocalstorage_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_qmlls_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_qmlmeta.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_qmlmeta_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_qmlmodels.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_qmlmodels_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_qmlnetwork.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_qmlnetwork_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_qmltest.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_qmltest_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_qmltoolingsettings_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_qmltyperegistrar_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_qmlworkerscript.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_qmlworkerscript_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_qmlxmllistmodel.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_qmlxmllistmodel_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quick.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quick3d.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quick3d_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quick3dassetimport.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quick3dassetimport_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quick3dassetutils.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quick3dassetutils_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quick3deffects.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quick3dglslparser_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quick3dhelpers.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quick3dhelpers_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quick3dhelpersimpl.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quick3dhelpersimpl_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quick3diblbaker.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quick3diblbaker_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quick3dparticleeffects.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quick3dparticles.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quick3dparticles_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quick3druntimerender.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quick3druntimerender_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quick3dspatialaudio_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quick3dutils.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quick3dutils_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quick3dxr.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quick3dxr_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quick_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2basic.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2basic_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2basicstyleimpl.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2basicstyleimpl_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2fluentwinui3styleimpl.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2fluentwinui3styleimpl_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2fusion.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2fusion_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2fusionstyleimpl.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2fusionstyleimpl_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2imagine.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2imagine_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2imaginestyleimpl.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2impl.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2impl_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2material.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2material_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2materialstyleimpl.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2materialstyleimpl_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2universal.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2universal_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2universalstyleimpl.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2universalstyleimpl_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrolstestutilsprivate_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quickdialogs2.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quickdialogs2_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quickdialogs2quickimpl.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quickdialogs2quickimpl_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quickdialogs2utils.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quickdialogs2utils_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quickeffects.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quickeffects_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quicklayouts.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quicklayouts_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quickparticles_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quickshapes_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quickshapesdesignhelpers_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quicktemplates2.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quicktestutilsprivate_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quicktimeline.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quicktimeline_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quicktimelineblendtrees.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quicktimelineblendtrees_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quickvectorimage.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quickvectorimage_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quickvectorimagegenerator_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quickvectorimagehelpers.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quickvectorimagehelpers_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quickwidgets.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quickwidgets_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_sensors.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_sensors_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_sensorsquick.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_sensorsquick_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_shadertools.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_shadertools_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_spatialaudio.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_spatialaudio_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_sql.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_sql_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_svg.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_svg_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_svgwidgets.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_testinternals_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_testlib.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_testlib_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_texttospeech.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_texttospeech_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_tools_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_uiplugin.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_uitools.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_uitools_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_virtualkeyboard.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_virtualkeyboard_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_virtualkeyboardqml.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_virtualkeyboardqml_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_virtualkeyboardsettings.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_virtualkeyboardsettings_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_wayland_egl_compositor_hw_integration_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_waylandclient.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_waylandclient_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_waylandclientfeatures_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_waylandcompositor.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_waylandcompositor_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_waylandcompositoriviapplication.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_waylandcompositoriviapplication_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_waylandcompositorpresentationtime.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_waylandcompositorpresentationtime_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_waylandcompositorwlshell.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_waylandcompositorwlshell_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_waylandcompositorxdgshell.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_waylandcompositorxdgshell_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_waylandglobal_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_webchannel.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_webchannel_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_webchannelquick.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_webchannelquick_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_webenginecore.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_webenginecore_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_webenginequick.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_webenginequick_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_webenginequickdelegatesqml.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_webenginewidgets.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_webenginewidgets_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_websockets.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_websockets_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_widgets.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_wl_shell_integration_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_xml.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_xml_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_QCoroCore.pri:
/usr/lib/qt6/mkspecs/modules/qt_QCoroCoro.pri:
/usr/lib/qt6/mkspecs/modules/qt_QCoroDBus.pri:
/usr/lib/qt6/mkspecs/modules/qt_QCoroNetwork.pri:
/usr/lib/qt6/mkspecs/modules/qt_QCoroQml.pri:
/usr/lib/qt6/mkspecs/modules/qt_QCoroQuick.pri:
/usr/lib/qt6/mkspecs/modules/qt_QCoroTest.pri:
/usr/lib/qt6/mkspecs/modules/qt_QCoroWebSockets.pri:
/usr/lib/qt6/mkspecs/features/qt_functions.prf:
/usr/lib/qt6/mkspecs/features/qt_config.prf:
/usr/lib/qt6/mkspecs/linux-g++/qmake.conf:
/usr/lib/qt6/mkspecs/features/spec_post.prf:
.qmake.stash:
/usr/lib/qt6/mkspecs/features/exclusive_builds.prf:
/usr/lib/qt6/mkspecs/features/toolchain.prf:
/usr/lib/qt6/mkspecs/features/default_pre.prf:
/usr/lib/qt6/mkspecs/features/resolve_config.prf:
/usr/lib/qt6/mkspecs/features/default_post.prf:
/usr/lib/qt6/mkspecs/features/cmdline.prf:
/usr/lib/qt6/mkspecs/features/warn_on.prf:
/usr/lib/qt6/mkspecs/features/permissions.prf:
/usr/lib/qt6/mkspecs/features/qt.prf:
/usr/lib/qt6/mkspecs/features/resources_functions.prf:
/usr/lib/qt6/mkspecs/features/resources.prf:
/usr/lib/qt6/mkspecs/features/moc.prf:
/usr/lib/qt6/mkspecs/features/link_ltcg.prf:
/usr/lib/qt6/mkspecs/features/unix/opengl.prf:
/usr/lib/qt6/mkspecs/features/uic.prf:
/usr/lib/qt6/mkspecs/features/unix/no_direct_extern_access.prf:
/usr/lib/qt6/mkspecs/features/unix/thread.prf:
/usr/lib/qt6/mkspecs/features/qmake_use.prf:
/usr/lib/qt6/mkspecs/features/file_copies.prf:
/usr/lib/qt6/mkspecs/features/testcase_targets.prf:
/usr/lib/qt6/mkspecs/features/exceptions.prf:
/usr/lib/qt6/mkspecs/features/yacc.prf:
/usr/lib/qt6/mkspecs/features/lex.prf:
hellyeah.pro:
/usr/lib/libQt6Widgets.prl:
/usr/lib/libQt6Gui.prl:
/usr/lib/libQt6Network.prl:
/usr/lib/libQt6Sql.prl:
/usr/lib/libQt6Core.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile hellyeah.pro

qmake_all: FORCE


all: Makefile hellyeah

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents /usr/lib/qt6/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents src/api/HifiClient.hpp src/player/AudioPlayer.hpp src/ui/MainWindow.hpp src/ui/TrackItemWidget.hpp src/ui/FavoriteCard.hpp src/ui/AlbumCard.hpp src/db/DatabaseManager.hpp src/net/DownloadManager.hpp src/ui/CreateAlbumDialog.hpp $(DISTDIR)/
	$(COPY_FILE) --parents src/main.cpp src/api/HifiClient.cpp src/player/AudioPlayer.cpp src/ui/MainWindow.cpp src/ui/TrackItemWidget.cpp src/ui/FavoriteCard.cpp src/ui/AlbumCard.cpp src/db/DatabaseManager.cpp src/net/DownloadManager.cpp src/ui/CreateAlbumDialog.cpp $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: /usr/lib/qt6/mkspecs/features/data/dummy.cpp
	g++ -pipe -O2 -std=gnu++1z -Wall -Wextra -dM -E -o moc_predefs.h /usr/lib/qt6/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: moc_HifiClient.cpp moc_AudioPlayer.cpp moc_MainWindow.cpp moc_TrackItemWidget.cpp moc_FavoriteCard.cpp moc_AlbumCard.cpp moc_DatabaseManager.cpp moc_DownloadManager.cpp moc_CreateAlbumDialog.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_HifiClient.cpp moc_AudioPlayer.cpp moc_MainWindow.cpp moc_TrackItemWidget.cpp moc_FavoriteCard.cpp moc_AlbumCard.cpp moc_DatabaseManager.cpp moc_DownloadManager.cpp moc_CreateAlbumDialog.cpp
moc_HifiClient.cpp: src/api/HifiClient.hpp \
		moc_predefs.h \
		/usr/lib/qt6/moc
	/usr/lib/qt6/moc $(DEFINES) --include /home/xi/dev/hellyeah/moc_predefs.h -I/usr/lib/qt6/mkspecs/linux-g++ -I/home/xi/dev/hellyeah -I/usr/include/qt6 -I/usr/include/qt6/QtWidgets -I/usr/include/qt6/QtGui -I/usr/include/qt6/QtNetwork -I/usr/include/qt6/QtSql -I/usr/include/qt6/QtCore -I/usr/include/c++/15.2.1 -I/usr/include/c++/15.2.1/x86_64-pc-linux-gnu -I/usr/include/c++/15.2.1/backward -I/usr/lib/gcc/x86_64-pc-linux-gnu/15.2.1/include -I/usr/local/include -I/usr/lib/gcc/x86_64-pc-linux-gnu/15.2.1/include-fixed -I/usr/include src/api/HifiClient.hpp -o moc_HifiClient.cpp

moc_AudioPlayer.cpp: src/player/AudioPlayer.hpp \
		moc_predefs.h \
		/usr/lib/qt6/moc
	/usr/lib/qt6/moc $(DEFINES) --include /home/xi/dev/hellyeah/moc_predefs.h -I/usr/lib/qt6/mkspecs/linux-g++ -I/home/xi/dev/hellyeah -I/usr/include/qt6 -I/usr/include/qt6/QtWidgets -I/usr/include/qt6/QtGui -I/usr/include/qt6/QtNetwork -I/usr/include/qt6/QtSql -I/usr/include/qt6/QtCore -I/usr/include/c++/15.2.1 -I/usr/include/c++/15.2.1/x86_64-pc-linux-gnu -I/usr/include/c++/15.2.1/backward -I/usr/lib/gcc/x86_64-pc-linux-gnu/15.2.1/include -I/usr/local/include -I/usr/lib/gcc/x86_64-pc-linux-gnu/15.2.1/include-fixed -I/usr/include src/player/AudioPlayer.hpp -o moc_AudioPlayer.cpp

moc_MainWindow.cpp: src/ui/MainWindow.hpp \
		src/api/HifiClient.hpp \
		src/db/DatabaseManager.hpp \
		src/net/DownloadManager.hpp \
		src/player/AudioPlayer.hpp \
		src/ui/AlbumCard.hpp \
		src/ui/CreateAlbumDialog.hpp \
		src/ui/FavoriteCard.hpp \
		src/ui/TrackItemWidget.hpp \
		moc_predefs.h \
		/usr/lib/qt6/moc
	/usr/lib/qt6/moc $(DEFINES) --include /home/xi/dev/hellyeah/moc_predefs.h -I/usr/lib/qt6/mkspecs/linux-g++ -I/home/xi/dev/hellyeah -I/usr/include/qt6 -I/usr/include/qt6/QtWidgets -I/usr/include/qt6/QtGui -I/usr/include/qt6/QtNetwork -I/usr/include/qt6/QtSql -I/usr/include/qt6/QtCore -I/usr/include/c++/15.2.1 -I/usr/include/c++/15.2.1/x86_64-pc-linux-gnu -I/usr/include/c++/15.2.1/backward -I/usr/lib/gcc/x86_64-pc-linux-gnu/15.2.1/include -I/usr/local/include -I/usr/lib/gcc/x86_64-pc-linux-gnu/15.2.1/include-fixed -I/usr/include src/ui/MainWindow.hpp -o moc_MainWindow.cpp

moc_TrackItemWidget.cpp: src/ui/TrackItemWidget.hpp \
		moc_predefs.h \
		/usr/lib/qt6/moc
	/usr/lib/qt6/moc $(DEFINES) --include /home/xi/dev/hellyeah/moc_predefs.h -I/usr/lib/qt6/mkspecs/linux-g++ -I/home/xi/dev/hellyeah -I/usr/include/qt6 -I/usr/include/qt6/QtWidgets -I/usr/include/qt6/QtGui -I/usr/include/qt6/QtNetwork -I/usr/include/qt6/QtSql -I/usr/include/qt6/QtCore -I/usr/include/c++/15.2.1 -I/usr/include/c++/15.2.1/x86_64-pc-linux-gnu -I/usr/include/c++/15.2.1/backward -I/usr/lib/gcc/x86_64-pc-linux-gnu/15.2.1/include -I/usr/local/include -I/usr/lib/gcc/x86_64-pc-linux-gnu/15.2.1/include-fixed -I/usr/include src/ui/TrackItemWidget.hpp -o moc_TrackItemWidget.cpp

moc_FavoriteCard.cpp: src/ui/FavoriteCard.hpp \
		moc_predefs.h \
		/usr/lib/qt6/moc
	/usr/lib/qt6/moc $(DEFINES) --include /home/xi/dev/hellyeah/moc_predefs.h -I/usr/lib/qt6/mkspecs/linux-g++ -I/home/xi/dev/hellyeah -I/usr/include/qt6 -I/usr/include/qt6/QtWidgets -I/usr/include/qt6/QtGui -I/usr/include/qt6/QtNetwork -I/usr/include/qt6/QtSql -I/usr/include/qt6/QtCore -I/usr/include/c++/15.2.1 -I/usr/include/c++/15.2.1/x86_64-pc-linux-gnu -I/usr/include/c++/15.2.1/backward -I/usr/lib/gcc/x86_64-pc-linux-gnu/15.2.1/include -I/usr/local/include -I/usr/lib/gcc/x86_64-pc-linux-gnu/15.2.1/include-fixed -I/usr/include src/ui/FavoriteCard.hpp -o moc_FavoriteCard.cpp

moc_AlbumCard.cpp: src/ui/AlbumCard.hpp \
		moc_predefs.h \
		/usr/lib/qt6/moc
	/usr/lib/qt6/moc $(DEFINES) --include /home/xi/dev/hellyeah/moc_predefs.h -I/usr/lib/qt6/mkspecs/linux-g++ -I/home/xi/dev/hellyeah -I/usr/include/qt6 -I/usr/include/qt6/QtWidgets -I/usr/include/qt6/QtGui -I/usr/include/qt6/QtNetwork -I/usr/include/qt6/QtSql -I/usr/include/qt6/QtCore -I/usr/include/c++/15.2.1 -I/usr/include/c++/15.2.1/x86_64-pc-linux-gnu -I/usr/include/c++/15.2.1/backward -I/usr/lib/gcc/x86_64-pc-linux-gnu/15.2.1/include -I/usr/local/include -I/usr/lib/gcc/x86_64-pc-linux-gnu/15.2.1/include-fixed -I/usr/include src/ui/AlbumCard.hpp -o moc_AlbumCard.cpp

moc_DatabaseManager.cpp: src/db/DatabaseManager.hpp \
		moc_predefs.h \
		/usr/lib/qt6/moc
	/usr/lib/qt6/moc $(DEFINES) --include /home/xi/dev/hellyeah/moc_predefs.h -I/usr/lib/qt6/mkspecs/linux-g++ -I/home/xi/dev/hellyeah -I/usr/include/qt6 -I/usr/include/qt6/QtWidgets -I/usr/include/qt6/QtGui -I/usr/include/qt6/QtNetwork -I/usr/include/qt6/QtSql -I/usr/include/qt6/QtCore -I/usr/include/c++/15.2.1 -I/usr/include/c++/15.2.1/x86_64-pc-linux-gnu -I/usr/include/c++/15.2.1/backward -I/usr/lib/gcc/x86_64-pc-linux-gnu/15.2.1/include -I/usr/local/include -I/usr/lib/gcc/x86_64-pc-linux-gnu/15.2.1/include-fixed -I/usr/include src/db/DatabaseManager.hpp -o moc_DatabaseManager.cpp

moc_DownloadManager.cpp: src/net/DownloadManager.hpp \
		moc_predefs.h \
		/usr/lib/qt6/moc
	/usr/lib/qt6/moc $(DEFINES) --include /home/xi/dev/hellyeah/moc_predefs.h -I/usr/lib/qt6/mkspecs/linux-g++ -I/home/xi/dev/hellyeah -I/usr/include/qt6 -I/usr/include/qt6/QtWidgets -I/usr/include/qt6/QtGui -I/usr/include/qt6/QtNetwork -I/usr/include/qt6/QtSql -I/usr/include/qt6/QtCore -I/usr/include/c++/15.2.1 -I/usr/include/c++/15.2.1/x86_64-pc-linux-gnu -I/usr/include/c++/15.2.1/backward -I/usr/lib/gcc/x86_64-pc-linux-gnu/15.2.1/include -I/usr/local/include -I/usr/lib/gcc/x86_64-pc-linux-gnu/15.2.1/include-fixed -I/usr/include src/net/DownloadManager.hpp -o moc_DownloadManager.cpp

moc_CreateAlbumDialog.cpp: src/ui/CreateAlbumDialog.hpp \
		moc_predefs.h \
		/usr/lib/qt6/moc
	/usr/lib/qt6/moc $(DEFINES) --include /home/xi/dev/hellyeah/moc_predefs.h -I/usr/lib/qt6/mkspecs/linux-g++ -I/home/xi/dev/hellyeah -I/usr/include/qt6 -I/usr/include/qt6/QtWidgets -I/usr/include/qt6/QtGui -I/usr/include/qt6/QtNetwork -I/usr/include/qt6/QtSql -I/usr/include/qt6/QtCore -I/usr/include/c++/15.2.1 -I/usr/include/c++/15.2.1/x86_64-pc-linux-gnu -I/usr/include/c++/15.2.1/backward -I/usr/lib/gcc/x86_64-pc-linux-gnu/15.2.1/include -I/usr/local/include -I/usr/lib/gcc/x86_64-pc-linux-gnu/15.2.1/include-fixed -I/usr/include src/ui/CreateAlbumDialog.hpp -o moc_CreateAlbumDialog.cpp

compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_predefs_clean compiler_moc_header_clean 

####### Compile

main.o: src/main.cpp src/ui/MainWindow.hpp \
		src/api/HifiClient.hpp \
		src/db/DatabaseManager.hpp \
		src/net/DownloadManager.hpp \
		src/player/AudioPlayer.hpp \
		src/ui/AlbumCard.hpp \
		src/ui/CreateAlbumDialog.hpp \
		src/ui/FavoriteCard.hpp \
		src/ui/TrackItemWidget.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o src/main.cpp

HifiClient.o: src/api/HifiClient.cpp src/api/HifiClient.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o HifiClient.o src/api/HifiClient.cpp

AudioPlayer.o: src/player/AudioPlayer.cpp src/player/miniaudio.h \
		src/player/AudioPlayer.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o AudioPlayer.o src/player/AudioPlayer.cpp

MainWindow.o: src/ui/MainWindow.cpp src/ui/MainWindow.hpp \
		src/api/HifiClient.hpp \
		src/db/DatabaseManager.hpp \
		src/net/DownloadManager.hpp \
		src/player/AudioPlayer.hpp \
		src/ui/AlbumCard.hpp \
		src/ui/CreateAlbumDialog.hpp \
		src/ui/FavoriteCard.hpp \
		src/ui/TrackItemWidget.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o MainWindow.o src/ui/MainWindow.cpp

TrackItemWidget.o: src/ui/TrackItemWidget.cpp src/ui/TrackItemWidget.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o TrackItemWidget.o src/ui/TrackItemWidget.cpp

FavoriteCard.o: src/ui/FavoriteCard.cpp src/ui/FavoriteCard.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o FavoriteCard.o src/ui/FavoriteCard.cpp

AlbumCard.o: src/ui/AlbumCard.cpp src/ui/AlbumCard.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o AlbumCard.o src/ui/AlbumCard.cpp

DatabaseManager.o: src/db/DatabaseManager.cpp src/db/DatabaseManager.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o DatabaseManager.o src/db/DatabaseManager.cpp

DownloadManager.o: src/net/DownloadManager.cpp src/net/DownloadManager.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o DownloadManager.o src/net/DownloadManager.cpp

CreateAlbumDialog.o: src/ui/CreateAlbumDialog.cpp src/ui/CreateAlbumDialog.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o CreateAlbumDialog.o src/ui/CreateAlbumDialog.cpp

moc_HifiClient.o: moc_HifiClient.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_HifiClient.o moc_HifiClient.cpp

moc_AudioPlayer.o: moc_AudioPlayer.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_AudioPlayer.o moc_AudioPlayer.cpp

moc_MainWindow.o: moc_MainWindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_MainWindow.o moc_MainWindow.cpp

moc_TrackItemWidget.o: moc_TrackItemWidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_TrackItemWidget.o moc_TrackItemWidget.cpp

moc_FavoriteCard.o: moc_FavoriteCard.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_FavoriteCard.o moc_FavoriteCard.cpp

moc_AlbumCard.o: moc_AlbumCard.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_AlbumCard.o moc_AlbumCard.cpp

moc_DatabaseManager.o: moc_DatabaseManager.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_DatabaseManager.o moc_DatabaseManager.cpp

moc_DownloadManager.o: moc_DownloadManager.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_DownloadManager.o moc_DownloadManager.cpp

moc_CreateAlbumDialog.o: moc_CreateAlbumDialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_CreateAlbumDialog.o moc_CreateAlbumDialog.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

.SUFFIXES:

